export interface DriveFileItem {
  id: string;
  name: string;
  mimeType: string;
  webViewLink?: string;
  iconLink?: string;
  createdTime?: string;
  modifiedTime?: string;
  size?: string;
}

/**
 * List files from Google Drive using the user's access token
 */
export async function listDriveFiles(
  accessToken: string,
  options: {
    folderId?: string;
    searchTerm?: string;
    mimeType?: string;
    pageSize?: number;
  } = {}
): Promise<DriveFileItem[]> {
  const { folderId, searchTerm, mimeType, pageSize = 20 } = options;

  let queryParts: string[] = ['trashed = false'];

  if (folderId) {
    queryParts.push(`'${folderId}' in parents`);
  }

  if (searchTerm) {
    queryParts.push(`name contains '${searchTerm}'`);
  }

  if (mimeType) {
    queryParts.push(`mimeType = '${mimeType}'`);
  }

  const q = encodeURIComponent(queryParts.join(' and '));
  const fields = encodeURIComponent('files(id, name, mimeType, webViewLink, iconLink, createdTime, modifiedTime, size)');
  const url = `https://www.googleapis.com/drive/v3/files?q=${q}&pageSize=${pageSize}&fields=${fields}&orderBy=modifiedTime desc`;

  const res = await fetch(url, {
    headers: {
      Authorization: `Bearer ${accessToken}`,
      Accept: 'application/json'
    }
  });

  if (!res.ok) {
    const errorData = await res.json().catch(() => ({}));
    throw new Error(errorData.error?.message || `Drive API error: ${res.statusText}`);
  }

  const data = await res.json();
  return data.files || [];
}

/**
 * Scan target Drive folder or Drive root to calculate next sequence ID
 */
export async function calculateNextDriveSequence(
  accessToken: string,
  siteNo: string
): Promise<number> {
  try {
    const files = await listDriveFiles(accessToken, {
      searchTerm: siteNo,
      pageSize: 50
    });

    const regex = new RegExp(`^${siteNo}-(\\d{3})`, 'i');
    let maxSeq = 0;

    files.forEach((file) => {
      const match = file.name.match(regex);
      if (match && match[1]) {
        const seqNum = parseInt(match[1], 10);
        if (seqNum > maxSeq) {
          maxSeq = seqNum;
        }
      }
    });

    return maxSeq + 1;
  } catch (err) {
    console.warn('Could not query Drive for sequence count, using fallback sequence:', err);
    return 1;
  }
}

/**
 * Create an inspection report record in Google Drive
 */
export async function createDriveReportDocument(
  accessToken: string,
  options: {
    filename: string;
    folderId?: string;
    reportData: any;
  }
): Promise<DriveFileItem> {
  const { filename, folderId, reportData } = options;

  // Metadata for the file
  const metadata: { name: string; mimeType: string; parents?: string[]; description?: string } = {
    name: filename,
    mimeType: 'application/json',
    description: `BTO Photo Inspection Report for ${reportData.siteNo} generated by Ts. Azrin Helmi`
  };

  if (folderId) {
    metadata.parents = [folderId];
  }

  // Create file with metadata + report content
  const boundary = '-------314159265358979323846';
  const delimiter = `\r\n--${boundary}\r\n`;
  const closeDelimiter = `\r\n--${boundary}--`;

  const multipartRequestBody =
    delimiter +
    'Content-Type: application/json; charset=UTF-8\r\n\r\n' +
    JSON.stringify(metadata) +
    delimiter +
    'Content-Type: application/json\r\n\r\n' +
    JSON.stringify(reportData, null, 2) +
    closeDelimiter;

  const res = await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&fields=id,name,mimeType,webViewLink,createdTime', {
    method: 'POST',
    headers: {
      Authorization: `Bearer ${accessToken}`,
      'Content-Type': `multipart/related; boundary=${boundary}`
    },
    body: multipartRequestBody
  });

  if (!res.ok) {
    // If target folder is inaccessible or permission denied, retry creating in user's root Drive
    if (folderId) {
      return createDriveReportDocument(accessToken, {
        filename,
        reportData
      });
    }
    const errorData = await res.json().catch(() => ({}));
    throw new Error(errorData.error?.message || `Failed to create file in Google Drive: ${res.statusText}`);
  }

  return await res.json();
}

/**
 * Delete a file with explicit user confirmation
 */
export async function deleteDriveFile(accessToken: string, fileId: string): Promise<boolean> {
  const res = await fetch(`https://www.googleapis.com/drive/v3/files/${fileId}`, {
    method: 'DELETE',
    headers: {
      Authorization: `Bearer ${accessToken}`
    }
  });

  return res.ok;
}
